package edu.ndsu.finalProject.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import edu.ndsu.finalProject.cayenne.persistent.Lesson;

/**
 * Class _Course was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Course extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String COURSE_ID_PK_COLUMN = "course_id";

    public static final Property<String> ADDRESS = Property.create("address", String.class);
    public static final Property<String> EMAIL = Property.create("email", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> PHONE = Property.create("phone", String.class);
    public static final Property<String> WEBSITE = Property.create("website", String.class);
    public static final Property<List<Lesson>> LESSONS = Property.create("lessons", List.class);

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPhone(String phone) {
        writeProperty("phone", phone);
    }
    public String getPhone() {
        return (String)readProperty("phone");
    }

    public void setWebsite(String website) {
        writeProperty("website", website);
    }
    public String getWebsite() {
        return (String)readProperty("website");
    }

    public void addToLessons(Lesson obj) {
        addToManyTarget("lessons", obj, true);
    }
    public void removeFromLessons(Lesson obj) {
        removeToManyTarget("lessons", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lesson> getLessons() {
        return (List<Lesson>)readProperty("lessons");
    }


}
