package edu.ndsu.finalProject.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _InstructorWorking was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InstructorWorking extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String WORKING_ID_PK_COLUMN = "working_id";

    public static final Property<Integer> DATE_ID = Property.create("dateId", Integer.class);
    public static final Property<Integer> INSTRUCTOR_ID = Property.create("instructorId", Integer.class);

    public void setDateId(int dateId) {
        writeProperty("dateId", dateId);
    }
    public int getDateId() {
        Object value = readProperty("dateId");
        return (value != null) ? (Integer) value : 0;
    }

    public void setInstructorId(int instructorId) {
        writeProperty("instructorId", instructorId);
    }
    public int getInstructorId() {
        Object value = readProperty("instructorId");
        return (value != null) ? (Integer) value : 0;
    }

}
