package edu.ndsu.finalProject.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _UserAccount was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserAccount extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String USER_ID_PK_COLUMN = "user_id";

    public static final Property<String> EMAIL = Property.create("email", String.class);
    public static final Property<Boolean> GUARDIAN = Property.create("guardian", Boolean.class);
    public static final Property<Integer> GUARDIAN_ID = Property.create("guardianId", Integer.class);
    public static final Property<Boolean> INSTRUCTOR = Property.create("instructor", Boolean.class);
    public static final Property<Integer> INSTRUCTOR_ID = Property.create("instructorId", Integer.class);
    public static final Property<Boolean> INSTRUCTORSUPERVISOR = Property.create("instructorsupervisor", Boolean.class);
    public static final Property<String> PASSWORD_HASH = Property.create("passwordHash", String.class);
    public static final Property<String> PASSWORD_SALT = Property.create("passwordSalt", String.class);
    public static final Property<Integer> USER_ID = Property.create("userID", Integer.class);

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setGuardian(boolean guardian) {
        writeProperty("guardian", guardian);
    }
	public boolean isGuardian() {
        Boolean value = (Boolean)readProperty("guardian");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setGuardianId(int guardianId) {
        writeProperty("guardianId", guardianId);
    }
    public int getGuardianId() {
        Object value = readProperty("guardianId");
        return (value != null) ? (Integer) value : 0;
    }

    public void setInstructor(boolean instructor) {
        writeProperty("instructor", instructor);
    }
	public boolean isInstructor() {
        Boolean value = (Boolean)readProperty("instructor");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setInstructorId(int instructorId) {
        writeProperty("instructorId", instructorId);
    }
    public int getInstructorId() {
        Object value = readProperty("instructorId");
        return (value != null) ? (Integer) value : 0;
    }

    public void setInstructorsupervisor(boolean instructorsupervisor) {
        writeProperty("instructorsupervisor", instructorsupervisor);
    }
	public boolean isInstructorsupervisor() {
        Boolean value = (Boolean)readProperty("instructorsupervisor");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setPasswordHash(String passwordHash) {
        writeProperty("passwordHash", passwordHash);
    }
    public String getPasswordHash() {
        return (String)readProperty("passwordHash");
    }

    public void setPasswordSalt(String passwordSalt) {
        writeProperty("passwordSalt", passwordSalt);
    }
    public String getPasswordSalt() {
        return (String)readProperty("passwordSalt");
    }

    public void setUserID(Integer userID) {
        writeProperty("userID", userID);
    }
    public Integer getUserID() {
        return (Integer)readProperty("userID");
    }

}
