package edu.ndsu.assignment3.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _UserAccount was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserAccount extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PK_PK_COLUMN = "PK";

    public static final Property<Boolean> ADMIN = Property.create("admin", Boolean.class);
    public static final Property<String> EMAIL_ADDRESS = Property.create("emailAddress", String.class);
    public static final Property<Boolean> EMPLOYEE = Property.create("employee", Boolean.class);
    public static final Property<Boolean> MANAGER = Property.create("manager", Boolean.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> PASSWORD_HASH = Property.create("passwordHash", String.class);
    public static final Property<String> PASSWORD_SALT = Property.create("passwordSalt", String.class);
    public static final Property<String> USER_ID = Property.create("userID", String.class);

    public void setAdmin(boolean admin) {
        writeProperty("admin", admin);
    }
	public boolean isAdmin() {
        Boolean value = (Boolean)readProperty("admin");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setEmailAddress(String emailAddress) {
        writeProperty("emailAddress", emailAddress);
    }
    public String getEmailAddress() {
        return (String)readProperty("emailAddress");
    }

    public void setEmployee(boolean employee) {
        writeProperty("employee", employee);
    }
	public boolean isEmployee() {
        Boolean value = (Boolean)readProperty("employee");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setManager(boolean manager) {
        writeProperty("manager", manager);
    }
	public boolean isManager() {
        Boolean value = (Boolean)readProperty("manager");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPasswordHash(String passwordHash) {
        writeProperty("passwordHash", passwordHash);
    }
    public String getPasswordHash() {
        return (String)readProperty("passwordHash");
    }

    public void setPasswordSalt(String passwordSalt) {
        writeProperty("passwordSalt", passwordSalt);
    }
    public String getPasswordSalt() {
        return (String)readProperty("passwordSalt");
    }

    public void setUserID(String userID) {
        writeProperty("userID", userID);
    }
    public String getUserID() {
        return (String)readProperty("userID");
    }

}
