package edu.ndsu.finalProject.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Enrollment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Enrollment extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ENROLLMENT_ID_PK_COLUMN = "enrollment_id";

    public static final Property<Integer> LESSON_ID = Property.create("lessonId", Integer.class);
    public static final Property<Integer> STUDENT_ID = Property.create("studentId", Integer.class);

    public void setLessonId(int lessonId) {
        writeProperty("lessonId", lessonId);
    }
    public int getLessonId() {
        Object value = readProperty("lessonId");
        return (value != null) ? (Integer) value : 0;
    }

    public void setStudentId(int studentId) {
        writeProperty("studentId", studentId);
    }
    public int getStudentId() {
        Object value = readProperty("studentId");
        return (value != null) ? (Integer) value : 0;
    }

}
