package edu.ndsu.finalProject.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import edu.ndsu.finalProject.cayenne.persistent.Instructor;
import edu.ndsu.finalProject.cayenne.persistent.LessonDate;

/**
 * Class _InstructorWorking was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InstructorWorking extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String WORKING_ID_PK_COLUMN = "working_id";

    public static final Property<LessonDate> DATE = Property.create("date", LessonDate.class);
    public static final Property<Instructor> INSTRUCTOR = Property.create("instructor", Instructor.class);

    public void setDate(LessonDate date) {
        setToOneTarget("date", date, true);
    }

    public LessonDate getDate() {
        return (LessonDate)readProperty("date");
    }


    public void setInstructor(Instructor instructor) {
        setToOneTarget("instructor", instructor, true);
    }

    public Instructor getInstructor() {
        return (Instructor)readProperty("instructor");
    }


}
