package edu.ndsu.finalProject.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Instructor was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Instructor extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String INSTRUCTOR_ID_PK_COLUMN = "instructor_id";

    public static final Property<String> ADDRESS = Property.create("address", String.class);
    public static final Property<String> DATE_OF_BIRTH = Property.create("dateOfBirth", String.class);
    public static final Property<String> EMAIL = Property.create("email", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> PASSWORD_HASH = Property.create("passwordHash", String.class);
    public static final Property<String> PASSWORD_SALT = Property.create("passwordSalt", String.class);
    public static final Property<String> PHONE = Property.create("phone", String.class);
    public static final Property<Boolean> SUPERVISOR = Property.create("supervisor", Boolean.class);
    public static final Property<Float> WAGE = Property.create("wage", Float.class);

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setDateOfBirth(String dateOfBirth) {
        writeProperty("dateOfBirth", dateOfBirth);
    }
    public String getDateOfBirth() {
        return (String)readProperty("dateOfBirth");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPasswordHash(String passwordHash) {
        writeProperty("passwordHash", passwordHash);
    }
    public String getPasswordHash() {
        return (String)readProperty("passwordHash");
    }

    public void setPasswordSalt(String passwordSalt) {
        writeProperty("passwordSalt", passwordSalt);
    }
    public String getPasswordSalt() {
        return (String)readProperty("passwordSalt");
    }

    public void setPhone(String phone) {
        writeProperty("phone", phone);
    }
    public String getPhone() {
        return (String)readProperty("phone");
    }

    public void setSupervisor(boolean supervisor) {
        writeProperty("supervisor", supervisor);
    }
	public boolean isSupervisor() {
        Boolean value = (Boolean)readProperty("supervisor");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setWage(float wage) {
        writeProperty("wage", wage);
    }
    public float getWage() {
        Object value = readProperty("wage");
        return (value != null) ? (Float) value : 0;
    }

}
