package edu.ndsu.finalProject.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import edu.ndsu.finalProject.cayenne.persistent.InstructorWorking;
import edu.ndsu.finalProject.cayenne.persistent.Lesson;

/**
 * Class _LessonDate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LessonDate extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String DATE_ID_PK_COLUMN = "date_id";

    public static final Property<String> LESSON_DAY = Property.create("lessonDay", String.class);
    public static final Property<String> LESSON_TIME = Property.create("lessonTime", String.class);
    public static final Property<List<InstructorWorking>> INSTRUCTOR_WORKINGS = Property.create("instructorWorkings", List.class);
    public static final Property<Lesson> LESSON = Property.create("lesson", Lesson.class);

    public void setLessonDay(String lessonDay) {
        writeProperty("lessonDay", lessonDay);
    }
    public String getLessonDay() {
        return (String)readProperty("lessonDay");
    }

    public void setLessonTime(String lessonTime) {
        writeProperty("lessonTime", lessonTime);
    }
    public String getLessonTime() {
        return (String)readProperty("lessonTime");
    }

    public void addToInstructorWorkings(InstructorWorking obj) {
        addToManyTarget("instructorWorkings", obj, true);
    }
    public void removeFromInstructorWorkings(InstructorWorking obj) {
        removeToManyTarget("instructorWorkings", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InstructorWorking> getInstructorWorkings() {
        return (List<InstructorWorking>)readProperty("instructorWorkings");
    }


    public void setLesson(Lesson lesson) {
        setToOneTarget("lesson", lesson, true);
    }

    public Lesson getLesson() {
        return (Lesson)readProperty("lesson");
    }


}
