package edu.ndsu.finalProject.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import edu.ndsu.finalProject.cayenne.persistent.InstructorWorking;
import edu.ndsu.finalProject.cayenne.persistent.Lesson;

/**
 * Class _LessonDate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LessonDate extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String DATE_ID_PK_COLUMN = "date_id";

    public static final Property<String> LESSON_DATETIME = Property.create("lessonDatetime", String.class);
    public static final Property<Lesson> LESSON = Property.create("lesson", Lesson.class);
    public static final Property<List<InstructorWorking>> WORKINGS = Property.create("workings", List.class);

    public void setLessonDatetime(String lessonDatetime) {
        writeProperty("lessonDatetime", lessonDatetime);
    }
    public String getLessonDatetime() {
        return (String)readProperty("lessonDatetime");
    }

    public void setLesson(Lesson lesson) {
        setToOneTarget("lesson", lesson, true);
    }

    public Lesson getLesson() {
        return (Lesson)readProperty("lesson");
    }


    public void addToWorkings(InstructorWorking obj) {
        addToManyTarget("workings", obj, true);
    }
    public void removeFromWorkings(InstructorWorking obj) {
        removeToManyTarget("workings", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InstructorWorking> getWorkings() {
        return (List<InstructorWorking>)readProperty("workings");
    }


}
